# Rule Extraction — Tree-Based Classification Rules (Stage 4–5)

Trains dedicated **shallow** rule models (Random Forest + Decision Tree) on the
best feature-selection set from the benchmark, walks every root→leaf path into IF-THEN
rules, scores them, and cross-checks the two models.

**Prerequisite:** Run `02_Benchmark.ipynb` (the benchmark) first.

**Output per dataset** (`outputs/{dataset}/rules/`)
```
rules/
  rf/        rules.json · rules.csv · rules_with_probes.csv · rules_human.txt ·
             rules_summary.json · genes_in_rules.csv
  dt/        rules.json · rules.csv · rules_with_probes.csv · rules_human.txt ·
             rules_summary.json · genes_in_rules.csv
  compare/   crosscheck.json   (rules / literals confirmed by BOTH models)
```

`rules.csv` antecedents are gene-level (e.g. `ERBB2>8.12`); `rules_with_probes.csv`
spells out the exact probe ID(s) backing each condition instead (useful when
several probes collapse to one gene and you need to know which one fired).
`genes_in_rules.csv` is the distinct gene list actually used by the *surviving*
rules — not the full SHAP top-K — with backing probe IDs, rule counts, and
which classes each gene appears in.

**Config:** `configs/interpretation.yaml → interpretation.rules`

**Metrics** — *data-based*: support, confidence, error, lift, class_specificity ·
*prediction-based*: **fidelity** (agreement with the source model, used by the
rule-guided ANN in stage 10) · *set-level*: coverage, mean_fidelity.

## Setup

In [1]:
import sys
import json
import warnings
from pathlib import Path

# Make src.* importable from the notebooks/ directory
REPO_ROOT = Path("..").resolve()
sys.path.insert(0, str(REPO_ROOT))

warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=UserWarning, module="sklearn")

import numpy as np
import pandas as pd

from src.pipeline import GeneExpressionPipeline

pipe = GeneExpressionPipeline(
    config_root=str(REPO_ROOT / "configs"),
    output_root=str(REPO_ROOT / "outputs"),
    use_wandb=False,
)

## Run Rule Extraction

Picks the best FS set (by benchmark RF), then trains the shallow rule models
configured in `interpretation.rules.models` (default `rf` + `decisiontree`) and
extracts rules from each.

`pipe.run_rule_extraction(['GEO-Breast-20711'])` — specific datasets  
`pipe.run_rule_extraction()` — all enabled datasets

In [2]:
results = pipe.run_rule_extraction(dataset_names=None)
results

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Rule Extraction — Tree-Based Classification Rules                                                               │
│ Stage 4-5: dedicated RF/DecisionTree rule models per dataset                                                    │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

──────────────────────────────────────────── Dataset: GEO-Breast-20711 ────────────────────────────────────────────

    Best FS feature set: mrmr_miq (by balanced_accuracy)

  ✓ Reused prebuilt mapping: 45,118 probe→gene entries from GSE20711_mapping.csv

  → Rule extraction (rf)

  ✓ Extracted 1,842 raw rules from 200 tree(s)

  ✓ Simplified -> 80 rules across 4 class(es)

  ✓ Saved 80 rules -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Breast-20711\rules\rf

  → SHAP (rule model · rf)

  SHAP explainer: tree (model=RandomForestClassifier)
  Probe->gene collapse: 50 probes -> 45 genes (6 unmapped)
  Provenance -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Breast-20711\rules\rf\shap\text\probe_to_gene_metadata.csv
  SHAP plots saved -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Breast-20711\rules\rf\shap\plots
  SHAP matrix -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Breast-20711\rules\rf\shap\text\shap_feature_importance_matrix.csv
  Gene lists -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Breast-20711\rules\rf\shap\text\top_shap_genes_by_class.txt

  ✓ SHAP complete → C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Breast-20711\rules\rf\shap

  → Rule extraction (decisiontree)

  ✓ Extracted 10 raw rules from 1 tree(s)

  ✓ Simplified -> 4 rules across 4 class(es)

  ✓ Saved 4 rules -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Breast-20711\rules\dt

  → SHAP (rule model · decisiontree)

  SHAP explainer: tree (model=DecisionTreeClassifier)
  Probe->gene collapse: 50 probes -> 45 genes (6 unmapped)
  Provenance -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Breast-20711\rules\dt\shap\text\probe_to_gene_metadata.csv
  SHAP plots saved -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Breast-20711\rules\dt\shap\plots
  SHAP matrix -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Breast-20711\rules\dt\shap\text\shap_feature_importance_matrix.csv
  Gene lists -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Breast-20711\rules\dt\shap\text\top_shap_genes_by_class.txt

  ✓ SHAP complete → C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Breast-20711\rules\dt\shap

  ✓ Cross-check rf vs decisiontree: 1 identical rule(s), 13 shared gene-direction literal(s) (literal Jaccard=0.11)
-> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Breast-20711\rules\compare

           GEO-Breast-20711 — extracted rules (FS: mrmr_miq)
┏━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┓
┃        model ┃ n_rules ┃ cls:Basal ┃ cls:HER2 ┃ cls:LumA ┃ cls:LumB ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━┩
│           rf │      80 │        20 │       20 │       20 │       20 │
│ decisiontree │       4 │         1 │        1 │        1 │        1 │
└──────────────┴─────────┴───────────┴──────────┴──────────┴──────────┘

    Cross-check: 1 identical rule(s), 13 shared gene-direction literal(s) (literal Jaccard=0.11)

───────────────────────────────────────── Dataset: GEO-Mesothelioma-29354 ─────────────────────────────────────────

    Best FS feature set: boruta (by balanced_accuracy)

  → Parsing annotation file: GPL96.annot.gz

  ✓ Annotation file mapped 21,146/22,215 probes

  → Rule extraction (rf)

  ✓ Extracted 1,388 raw rules from 200 tree(s)

  ✓ Simplified -> 60 rules across 3 class(es)

  ✓ Saved 60 rules -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Mesothelioma-29354\rules\rf

  → SHAP (rule model · rf)

  SHAP explainer: tree (model=RandomForestClassifier)
  Probe->gene collapse: 7 probes -> 6 genes (0 unmapped)
  Provenance -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Mesothelioma-29354\rules\rf\shap\text\probe_to_gene_metadata.csv
  SHAP plots saved -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Mesothelioma-29354\rules\rf\shap\plots
  SHAP matrix -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Mesothelioma-29354\rules\rf\shap\text\shap_feature_importance_matrix.csv
  Gene lists -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Mesothelioma-29354\rules\rf\shap\text\top_shap_genes_by_class.txt

  ✓ SHAP complete → C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Mesothelioma-29354\rules\rf\shap

  → Rule extraction (decisiontree)

  ✓ Extracted 6 raw rules from 1 tree(s)

  ✓ Simplified -> 4 rules across 3 class(es)

  ✓ Saved 4 rules -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Mesothelioma-29354\rules\dt

  → SHAP (rule model · decisiontree)

  SHAP explainer: tree (model=DecisionTreeClassifier)
  Probe->gene collapse: 7 probes -> 6 genes (0 unmapped)
  Provenance -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Mesothelioma-29354\rules\dt\shap\text\probe_to_gene_metadata.csv
  SHAP plots saved -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Mesothelioma-29354\rules\dt\shap\plots
  SHAP matrix -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Mesothelioma-29354\rules\dt\shap\text\shap_feature_importance_matrix.csv
  Gene lists -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Mesothelioma-29354\rules\dt\shap\text\top_shap_genes_by_class.txt

  ✓ SHAP complete → C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Mesothelioma-29354\rules\dt\shap

  ✓ Cross-check rf vs decisiontree: 3 identical rule(s), 8 shared gene-direction literal(s) (literal Jaccard=0.31)
-> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Mesothelioma-29354\rules\compare

  GEO-Mesothelioma-29354 — extracted rules (FS:
                     boruta)
┏━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃        model ┃ n_rules ┃ cls:0 ┃ cls:1 ┃ cls:2 ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━┩
│           rf │      60 │    20 │    20 │    20 │
│ decisiontree │       4 │     1 │     2 │     1 │
└──────────────┴─────────┴───────┴───────┴───────┘

    Cross-check: 3 identical rule(s), 8 shared gene-direction literal(s) (literal Jaccard=0.31)

──────────────────────────────────────────── Dataset: GEO-Kidney-36895 ────────────────────────────────────────────

    Best FS feature set: boruta (by balanced_accuracy)

  Warning: removing 4 class(es) with < 2 samples: [1, 5, 7, 9]

  → Parsing annotation file: GPL570.annot.gz

  ✓ Annotation file mapped 45,118/54,623 probes

  → Rule extraction (rf)

  ✓ Extracted 1,808 raw rules from 200 tree(s)

  ✓ Simplified -> 100 rules across 6 class(es)

  ✓ Saved 100 rules -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Kidney-36895\rules\rf

  → SHAP (rule model · rf)

  SHAP explainer: tree (model=RandomForestClassifier)
  Probe->gene collapse: 7 probes -> 7 genes (1 unmapped)
  Provenance -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Kidney-36895\rules\rf\shap\text\probe_to_gene_metadata.csv
  SHAP plots saved -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Kidney-36895\rules\rf\shap\plots
  SHAP matrix -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Kidney-36895\rules\rf\shap\text\shap_feature_importance_matrix.csv
  Gene lists -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Kidney-36895\rules\rf\shap\text\top_shap_genes_by_class.txt

  ✓ SHAP complete → C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Kidney-36895\rules\rf\shap

  → Rule extraction (decisiontree)

  ✓ Extracted 9 raw rules from 1 tree(s)

  ✓ Simplified -> 6 rules across 6 class(es)

  ✓ Saved 6 rules -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Kidney-36895\rules\dt

  → SHAP (rule model · decisiontree)

  SHAP explainer: tree (model=DecisionTreeClassifier)
  Probe->gene collapse: 7 probes -> 7 genes (1 unmapped)
  Provenance -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Kidney-36895\rules\dt\shap\text\probe_to_gene_metadata.csv
  SHAP plots saved -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Kidney-36895\rules\dt\shap\plots
  SHAP matrix -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Kidney-36895\rules\dt\shap\text\shap_feature_importance_matrix.csv
  Gene lists -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Kidney-36895\rules\dt\shap\text\top_shap_genes_by_class.txt

  ✓ SHAP complete → C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Kidney-36895\rules\dt\shap

  ✓ Cross-check rf vs decisiontree: 1 identical rule(s), 17 shared gene-direction literal(s) (literal Jaccard=0.28)
-> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Kidney-36895\rules\compare

             GEO-Kidney-36895 — extracted rules (FS: boruta)
┏━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃        model ┃ n_rules ┃ cls:0 ┃ cls:1 ┃ cls:2 ┃ cls:3 ┃ cls:4 ┃ cls:6 ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━┩
│           rf │     100 │    10 │    20 │    20 │    20 │    20 │    10 │
│ decisiontree │       6 │     1 │     1 │     1 │     1 │     1 │     1 │
└──────────────┴─────────┴───────┴───────┴───────┴───────┴───────┴───────┘

    Cross-check: 1 identical rule(s), 17 shared gene-direction literal(s) (literal Jaccard=0.28)

──────────────────────────────────────────── Dataset: GEO-Colon-68468 ─────────────────────────────────────────────

    Best FS feature set: mrmr_miq (by balanced_accuracy)

  Warning: removing 2 class(es) with < 2 samples: [0, 4]

  → Parsing annotation file: GPL96.annot.gz

  ✓ Annotation file mapped 21,156/22,225 probes

  → Rule extraction (rf)

  ✓ Extracted 2,306 raw rules from 200 tree(s)

  ✓ Simplified -> 80 rules across 4 class(es)

  ✓ Saved 80 rules -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Colon-68468\rules\rf

  → SHAP (rule model · rf)

Background dataset has 388 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=388 when initializing the masker.

  SHAP explainer: tree (model=RandomForestClassifier)
  Probe->gene collapse: 50 probes -> 42 genes (0 unmapped)
  Provenance -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Colon-68468\rules\rf\shap\text\probe_to_gene_metadata.csv
  SHAP plots saved -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Colon-68468\rules\rf\shap\plots
  SHAP matrix -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Colon-68468\rules\rf\shap\text\shap_feature_importance_matrix.csv
  Gene lists -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Colon-68468\rules\rf\shap\text\top_shap_genes_by_class.txt

  ✓ SHAP complete → C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Colon-68468\rules\rf\shap

  → Rule extraction (decisiontree)

  ✓ Extracted 12 raw rules from 1 tree(s)

  ✓ Simplified -> 7 rules across 4 class(es)

  ✓ Saved 7 rules -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Colon-68468\rules\dt

  → SHAP (rule model · decisiontree)

Background dataset has 388 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=388 when initializing the masker.

  SHAP explainer: tree (model=DecisionTreeClassifier)
  Probe->gene collapse: 50 probes -> 42 genes (0 unmapped)
  Provenance -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Colon-68468\rules\dt\shap\text\probe_to_gene_metadata.csv
  SHAP plots saved -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Colon-68468\rules\dt\shap\plots
  SHAP matrix -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Colon-68468\rules\dt\shap\text\shap_feature_importance_matrix.csv
  Gene lists -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Colon-68468\rules\dt\shap\text\top_shap_genes_by_class.txt

  ✓ SHAP complete → C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Colon-68468\rules\dt\shap

  ✓ Cross-check rf vs decisiontree: 1 identical rule(s), 18 shared gene-direction literal(s) (literal Jaccard=0.22)
-> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Colon-68468\rules\compare

     GEO-Colon-68468 — extracted rules (FS: mrmr_miq)
┏━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃        model ┃ n_rules ┃ cls:0 ┃ cls:1 ┃ cls:2 ┃ cls:3 ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━┩
│           rf │      80 │    20 │    20 │    20 │    20 │
│ decisiontree │       7 │     4 │     1 │     1 │     1 │
└──────────────┴─────────┴───────┴───────┴───────┴───────┘

    Cross-check: 1 identical rule(s), 18 shared gene-direction literal(s) (literal Jaccard=0.22)

───────────────────────────────────────── Dataset: GEO-MultiCancer-68606 ──────────────────────────────────────────

    Best FS feature set: boruta (by balanced_accuracy)

  Warning: removing 1 class(es) with < 2 samples: [14]

  → Parsing annotation file: GPL96.annot.gz

  ✓ Annotation file mapped 21,156/22,225 probes

  → Rule extraction (rf)

  ✓ Extracted 1,525 raw rules from 200 tree(s)

  ✓ Simplified -> 100 rules across 10 class(es)

  ✓ Saved 100 rules -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-MultiCancer-68606\rules\rf

  → SHAP (rule model · rf)

  SHAP explainer: tree (model=RandomForestClassifier)
  Probe->gene collapse: 74 probes -> 72 genes (0 unmapped)
  Provenance -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-MultiCancer-68606\rules\rf\shap\text\probe_to_gene_metadata.csv
  SHAP plots saved -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-MultiCancer-68606\rules\rf\shap\plots
  SHAP matrix -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-MultiCancer-68606\rules\rf\shap\text\shap_feature_importance_matrix.csv
  Gene lists -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-MultiCancer-68606\rules\rf\shap\text\top_shap_genes_by_class.txt

  ✓ SHAP complete → C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-MultiCancer-68606\rules\rf\shap

  → Rule extraction (decisiontree)

  ✓ Extracted 9 raw rules from 1 tree(s)

  ✓ Simplified -> 3 rules across 3 class(es)

  ✓ Saved 3 rules -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-MultiCancer-68606\rules\dt

  → SHAP (rule model · decisiontree)

  SHAP explainer: tree (model=DecisionTreeClassifier)
  Probe->gene collapse: 74 probes -> 72 genes (0 unmapped)
  Provenance -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-MultiCancer-68606\rules\dt\shap\text\probe_to_gene_metadata.csv
  SHAP plots saved -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-MultiCancer-68606\rules\dt\shap\plots
  SHAP matrix -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-MultiCancer-68606\rules\dt\shap\text\shap_feature_importance_matrix.csv
  Gene lists -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-MultiCancer-68606\rules\dt\shap\text\top_shap_genes_by_class.txt

  ✓ SHAP complete → C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-MultiCancer-68606\rules\dt\shap

  ✓ Cross-check rf vs decisiontree: 0 identical rule(s), 6 shared gene-direction literal(s) (literal Jaccard=0.03)
-> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-MultiCancer-68606\rules\compare

                               GEO-MultiCancer-68606 — extracted rules (FS: boruta)
┏━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━┳━━━━━━━━┳━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃       model ┃ n_rules ┃ cls:0 ┃ cls:10 ┃  cls:11 ┃ cls:12 ┃ cls:13 ┃   cls:2 ┃  cls:3 ┃  cls:5 ┃  cls:8 ┃ cls:9 ┃
┡━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━╇━━━━━━━━╇━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│          rf │     100 │    16 │ 6.0000 │ 20.0000 │ 2.0000 │     20 │ 10.0000 │ 4.0000 │ 6.0000 │ 8.0000 │     8 │
│ decisiontr… │       3 │     1 │    nan │     nan │    nan │      1 │     nan │    nan │    nan │    nan │     1 │
└─────────────┴─────────┴───────┴────────┴─────────┴────────┴────────┴─────────┴────────┴────────┴────────┴───────┘

    Cross-check: 0 identical rule(s), 6 shared gene-direction literal(s) (literal Jaccard=0.03)

─────────────────────────────────────────── Dataset: CuMiDa-Ovary-6008 ────────────────────────────────────────────

    Best FS feature set: boruta (by balanced_accuracy)

  ✓ Reused prebuilt mapping: 21,225 probe→gene entries from GSE6008_mapping.csv

  → Rule extraction (rf)

  ✓ Extracted 2,000 raw rules from 200 tree(s)

  ✓ Simplified -> 80 rules across 4 class(es)

  ✓ Saved 80 rules -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Ovary-6008\rules\rf

  → SHAP (rule model · rf)

  SHAP explainer: tree (model=RandomForestClassifier)
  Probe->gene collapse: 177 probes -> 139 genes (2 unmapped)
  Provenance -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Ovary-6008\rules\rf\shap\text\probe_to_gene_metadata.csv
  SHAP plots saved -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Ovary-6008\rules\rf\shap\plots
  SHAP matrix -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Ovary-6008\rules\rf\shap\text\shap_feature_importance_matrix.csv
  Gene lists -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Ovary-6008\rules\rf\shap\text\top_shap_genes_by_class.txt

  ✓ SHAP complete → C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Ovary-6008\rules\rf\shap

  → Rule extraction (decisiontree)

  ✓ Extracted 10 raw rules from 1 tree(s)

  ✓ Simplified -> 7 rules across 4 class(es)

  ✓ Saved 7 rules -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Ovary-6008\rules\dt

  → SHAP (rule model · decisiontree)

  SHAP explainer: tree (model=DecisionTreeClassifier)
  Probe->gene collapse: 177 probes -> 139 genes (2 unmapped)
  Provenance -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Ovary-6008\rules\dt\shap\text\probe_to_gene_metadata.csv
  SHAP plots saved -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Ovary-6008\rules\dt\shap\plots
  SHAP matrix -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Ovary-6008\rules\dt\shap\text\shap_feature_importance_matrix.csv
  Gene lists -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Ovary-6008\rules\dt\shap\text\top_shap_genes_by_class.txt

  ✓ SHAP complete → C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Ovary-6008\rules\dt\shap

  ✓ Cross-check rf vs decisiontree: 1 identical rule(s), 13 shared gene-direction literal(s) (literal Jaccard=0.07)
-> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Ovary-6008\rules\compare

     CuMiDa-Ovary-6008 — extracted rules (FS: boruta)
┏━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃        model ┃ n_rules ┃ cls:0 ┃ cls:1 ┃ cls:2 ┃ cls:3 ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━┩
│           rf │      80 │    20 │    20 │    20 │    20 │
│ decisiontree │       7 │     1 │     3 │     1 │     2 │
└──────────────┴─────────┴───────┴───────┴───────┴───────┘

    Cross-check: 1 identical rule(s), 13 shared gene-direction literal(s) (literal Jaccard=0.07)

─────────────────────────────────────────── Dataset: CuMiDa-Brain-15824 ───────────────────────────────────────────

    Best FS feature set: boruta (by balanced_accuracy)

  ✓ Reused prebuilt mapping: 45,782 probe→gene entries from GSE15824_mapping.csv

  → Rule extraction (rf)

  ✓ Extracted 991 raw rules from 200 tree(s)

  ✓ Simplified -> 80 rules across 4 class(es)

  ✓ Saved 80 rules -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Brain-15824\rules\rf

  → SHAP (rule model · rf)

  SHAP explainer: tree (model=RandomForestClassifier)
  Probe->gene collapse: 103 probes -> 100 genes (9 unmapped)
  Provenance -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Brain-15824\rules\rf\shap\text\probe_to_gene_metadata.csv
  SHAP plots saved -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Brain-15824\rules\rf\shap\plots
  SHAP matrix -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Brain-15824\rules\rf\shap\text\shap_feature_importance_matrix.csv
  Gene lists -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Brain-15824\rules\rf\shap\text\top_shap_genes_by_class.txt

  ✓ SHAP complete → C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Brain-15824\rules\rf\shap

  → Rule extraction (decisiontree)

  ✓ Extracted 5 raw rules from 1 tree(s)

  ✓ Simplified -> 5 rules across 4 class(es)

  ✓ Saved 5 rules -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Brain-15824\rules\dt

  → SHAP (rule model · decisiontree)

  SHAP explainer: tree (model=DecisionTreeClassifier)
  Probe->gene collapse: 103 probes -> 100 genes (9 unmapped)
  Provenance -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Brain-15824\rules\dt\shap\text\probe_to_gene_metadata.csv
  SHAP plots saved -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Brain-15824\rules\dt\shap\plots
  SHAP matrix -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Brain-15824\rules\dt\shap\text\shap_feature_importance_matrix.csv
  Gene lists -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Brain-15824\rules\dt\shap\text\top_shap_genes_by_class.txt

  ✓ SHAP complete → C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Brain-15824\rules\dt\shap

  ✓ Cross-check rf vs decisiontree: 1 identical rule(s), 9 shared gene-direction literal(s) (literal Jaccard=0.07)
-> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Brain-15824\rules\compare

    CuMiDa-Brain-15824 — extracted rules (FS: boruta)
┏━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃        model ┃ n_rules ┃ cls:0 ┃ cls:1 ┃ cls:2 ┃ cls:3 ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━┩
│           rf │      80 │    20 │    20 │    20 │    20 │
│ decisiontree │       5 │     1 │     2 │     1 │     1 │
└──────────────┴─────────┴───────┴───────┴───────┴───────┘

    Cross-check: 1 identical rule(s), 9 shared gene-direction literal(s) (literal Jaccard=0.07)

────────────────────────────────────────── Dataset: CuMiDa-Breast-26304 ───────────────────────────────────────────

    Best FS feature set: mrmr_miq (by balanced_accuracy)

  ✓ Reused prebuilt mapping: 18,712 probe→gene entries from GSE26304_mapping.csv

  → Rule extraction (rf)

  ✓ Extracted 2,822 raw rules from 200 tree(s)

  ✓ Simplified -> 80 rules across 4 class(es)

  ✓ Saved 80 rules -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Breast-26304\rules\rf

  → SHAP (rule model · rf)

Background dataset has 115 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=115 when initializing the masker.

  SHAP explainer: tree (model=RandomForestClassifier)
  Probe->gene collapse: 50 probes -> 50 genes (21 unmapped)
  Provenance -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Breast-26304\rules\rf\shap\text\probe_to_gene_metadata.csv
  SHAP plots saved -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Breast-26304\rules\rf\shap\plots
  SHAP matrix -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Breast-26304\rules\rf\shap\text\shap_feature_importance_matrix.csv
  Gene lists -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Breast-26304\rules\rf\shap\text\top_shap_genes_by_class.txt

  ✓ SHAP complete → C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Breast-26304\rules\rf\shap

  → Rule extraction (decisiontree)

  ✓ Extracted 19 raw rules from 1 tree(s)

  ✓ Simplified -> 9 rules across 4 class(es)

  ✓ Saved 9 rules -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Breast-26304\rules\dt

  → SHAP (rule model · decisiontree)

Background dataset has 115 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=115 when initializing the masker.

  SHAP explainer: tree (model=DecisionTreeClassifier)
  Probe->gene collapse: 50 probes -> 50 genes (21 unmapped)
  Provenance -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Breast-26304\rules\dt\shap\text\probe_to_gene_metadata.csv
  SHAP plots saved -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Breast-26304\rules\dt\shap\plots
  SHAP matrix -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Breast-26304\rules\dt\shap\text\shap_feature_importance_matrix.csv
  Gene lists -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Breast-26304\rules\dt\shap\text\top_shap_genes_by_class.txt

  ✓ SHAP complete → C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Breast-26304\rules\dt\shap

  ✓ Cross-check rf vs decisiontree: 0 identical rule(s), 23 shared gene-direction literal(s) (literal Jaccard=0.15)
-> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Breast-26304\rules\compare

   CuMiDa-Breast-26304 — extracted rules (FS: mrmr_miq)
┏━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃        model ┃ n_rules ┃ cls:0 ┃ cls:1 ┃ cls:2 ┃ cls:3 ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━┩
│           rf │      80 │    20 │    20 │    20 │    20 │
│ decisiontree │       9 │     3 │     3 │     2 │     1 │
└──────────────┴─────────┴───────┴───────┴───────┴───────┘

    Cross-check: 0 identical rule(s), 23 shared gene-direction literal(s) (literal Jaccard=0.15)

───────────────────────────────────────── Dataset: CuMiDa-Leukemia-28497 ──────────────────────────────────────────

    Best FS feature set: boruta (by balanced_accuracy)

  ✓ Reused prebuilt mapping: 21,225 probe→gene entries from GSE28497_mapping.csv

  → Rule extraction (rf)

  ✓ Extracted 2,202 raw rules from 200 tree(s)

  ✓ Simplified -> 100 rules across 5 class(es)

  ✓ Saved 100 rules -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Leukemia-28497\rules\rf

  → SHAP (rule model · rf)

Background dataset has 281 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=281 when initializing the masker.

  SHAP explainer: tree (model=RandomForestClassifier)
  Probe->gene collapse: 357 probes -> 291 genes (0 unmapped)
  Provenance -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Leukemia-28497\rules\rf\shap\text\probe_to_gene_metadata.csv
  SHAP plots saved -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Leukemia-28497\rules\rf\shap\plots
  SHAP matrix -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Leukemia-28497\rules\rf\shap\text\shap_feature_importance_matrix.csv
  Gene lists -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Leukemia-28497\rules\rf\shap\text\top_shap_genes_by_class.txt

  ✓ SHAP complete → C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Leukemia-28497\rules\rf\shap

  → Rule extraction (decisiontree)

  ✓ Extracted 9 raw rules from 1 tree(s)

  ✓ Simplified -> 5 rules across 5 class(es)

  ✓ Saved 5 rules -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Leukemia-28497\rules\dt

  → SHAP (rule model · decisiontree)

Background dataset has 281 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=281 when initializing the masker.

  SHAP explainer: tree (model=DecisionTreeClassifier)
  Probe->gene collapse: 357 probes -> 291 genes (0 unmapped)
  Provenance -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Leukemia-28497\rules\dt\shap\text\probe_to_gene_metadata.csv
  SHAP plots saved -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Leukemia-28497\rules\dt\shap\plots
  SHAP matrix -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Leukemia-28497\rules\dt\shap\text\shap_feature_importance_matrix.csv
  Gene lists -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Leukemia-28497\rules\dt\shap\text\top_shap_genes_by_class.txt

  ✓ SHAP complete → C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Leukemia-28497\rules\dt\shap

  ✓ Cross-check rf vs decisiontree: 1 identical rule(s), 17 shared gene-direction literal(s) (literal Jaccard=0.08)
-> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Leukemia-28497\rules\compare

       CuMiDa-Leukemia-28497 — extracted rules (FS: boruta)
┏━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃        model ┃ n_rules ┃ cls:1 ┃ cls:2 ┃ cls:4 ┃ cls:5 ┃ cls:6 ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━┩
│           rf │     100 │    20 │    20 │    20 │    20 │    20 │
│ decisiontree │       5 │     1 │     1 │     1 │     1 │     1 │
└──────────────┴─────────┴───────┴───────┴───────┴───────┴───────┘

    Cross-check: 1 identical rule(s), 17 shared gene-direction literal(s) (literal Jaccard=0.08)

──────────────────────────────────────── Dataset: CuMiDa-Colorectal-41657 ─────────────────────────────────────────

    Best FS feature set: boruta (by balanced_accuracy)

  ✓ Reused prebuilt mapping: 19,697 probe→gene entries from GSE41657_mapping.csv

  → Rule extraction (rf)

  ✓ Extracted 1,733 raw rules from 200 tree(s)

  ✓ Simplified -> 80 rules across 4 class(es)

  ✓ Saved 80 rules -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Colorectal-41657\rules\rf

  → SHAP (rule model · rf)

  SHAP explainer: tree (model=RandomForestClassifier)
  Probe->gene collapse: 230 probes -> 229 genes (48 unmapped)
  Provenance -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Colorectal-41657\rules\rf\shap\text\probe_to_gene_metadata.csv
  SHAP plots saved -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Colorectal-41657\rules\rf\shap\plots
  SHAP matrix -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Colorectal-41657\rules\rf\shap\text\shap_feature_importance_matrix.csv
  Gene lists -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Colorectal-41657\rules\rf\shap\text\top_shap_genes_by_class.txt

  ✓ SHAP complete → C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Colorectal-41657\rules\rf\shap

  → Rule extraction (decisiontree)

  ✓ Extracted 10 raw rules from 1 tree(s)

  ✓ Simplified -> 5 rules across 4 class(es)

  ✓ Saved 5 rules -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Colorectal-41657\rules\dt

  → SHAP (rule model · decisiontree)

  SHAP explainer: tree (model=DecisionTreeClassifier)
  Probe->gene collapse: 230 probes -> 229 genes (48 unmapped)
  Provenance -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Colorectal-41657\rules\dt\shap\text\probe_to_gene_metadata.csv
  SHAP plots saved -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Colorectal-41657\rules\dt\shap\plots
  SHAP matrix -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Colorectal-41657\rules\dt\shap\text\shap_feature_importance_matrix.csv
  Gene lists -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Colorectal-41657\rules\dt\shap\text\top_shap_genes_by_class.txt

  ✓ SHAP complete → C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Colorectal-41657\rules\dt\shap

  ✓ Cross-check rf vs decisiontree: 0 identical rule(s), 9 shared gene-direction literal(s) (literal Jaccard=0.04)
-> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Colorectal-41657\rules\compare

  CuMiDa-Colorectal-41657 — extracted rules (FS: boruta)
┏━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃        model ┃ n_rules ┃ cls:0 ┃ cls:1 ┃ cls:2 ┃ cls:3 ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━┩
│           rf │      80 │    20 │    20 │    20 │    20 │
│ decisiontree │       5 │     1 │     2 │     1 │     1 │
└──────────────┴─────────┴───────┴───────┴───────┴───────┘

    Cross-check: 0 identical rule(s), 9 shared gene-direction literal(s) (literal Jaccard=0.04)

────────────────────────────────────────── Dataset: CuMiDa-Breast-45827 ───────────────────────────────────────────

    Best FS feature set: boruta (by balanced_accuracy)

  ✓ Reused prebuilt mapping: 45,782 probe→gene entries from GSE45827_mapping.csv

  → Rule extraction (rf)

  ✓ Extracted 1,721 raw rules from 200 tree(s)

  ✓ Simplified -> 100 rules across 6 class(es)

  ✓ Saved 100 rules -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Breast-45827\rules\rf

  → SHAP (rule model · rf)

Background dataset has 151 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=151 when initializing the masker.

  SHAP explainer: tree (model=RandomForestClassifier)
  Probe->gene collapse: 1509 probes -> 1271 genes (316 unmapped)
  Provenance -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Breast-45827\rules\rf\shap\text\probe_to_gene_metadata.csv
  SHAP plots saved -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Breast-45827\rules\rf\shap\plots
  SHAP matrix -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Breast-45827\rules\rf\shap\text\shap_feature_importance_matrix.csv
  Gene lists -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Breast-45827\rules\rf\shap\text\top_shap_genes_by_class.txt

  ✓ SHAP complete → C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Breast-45827\rules\rf\shap

  → Rule extraction (decisiontree)

  ✓ Extracted 9 raw rules from 1 tree(s)

  ✓ Simplified -> 6 rules across 6 class(es)

  ✓ Saved 6 rules -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Breast-45827\rules\dt

  → SHAP (rule model · decisiontree)

Background dataset has 151 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=151 when initializing the masker.

  SHAP explainer: tree (model=DecisionTreeClassifier)
  Probe->gene collapse: 1509 probes -> 1271 genes (316 unmapped)
  Provenance -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Breast-45827\rules\dt\shap\text\probe_to_gene_metadata.csv
  SHAP plots saved -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Breast-45827\rules\dt\shap\plots
  SHAP matrix -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Breast-45827\rules\dt\shap\text\shap_feature_importance_matrix.csv
  Gene lists -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Breast-45827\rules\dt\shap\text\top_shap_genes_by_class.txt

  ✓ SHAP complete → C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Breast-45827\rules\dt\shap

  ✓ Cross-check rf vs decisiontree: 0 identical rule(s), 6 shared gene-direction literal(s) (literal Jaccard=0.02)
-> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Breast-45827\rules\compare

            CuMiDa-Breast-45827 — extracted rules (FS: boruta)
┏━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃        model ┃ n_rules ┃ cls:0 ┃ cls:1 ┃ cls:2 ┃ cls:3 ┃ cls:4 ┃ cls:5 ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━┩
│           rf │     100 │    17 │    20 │    20 │    20 │     3 │    20 │
│ decisiontree │       6 │     1 │     1 │     1 │     1 │     1 │     1 │
└──────────────┴─────────┴───────┴───────┴───────┴───────┴───────┴───────┘

    Cross-check: 0 identical rule(s), 6 shared gene-direction literal(s) (literal Jaccard=0.02)

─────────────────────────────────────────── Dataset: CuMiDa-Brain-50161 ───────────────────────────────────────────

    Best FS feature set: boruta (by balanced_accuracy)

  ✓ Reused prebuilt mapping: 45,782 probe→gene entries from GSE50161_mapping.csv

  → Rule extraction (rf)

  ✓ Extracted 1,715 raw rules from 200 tree(s)

  ✓ Simplified -> 100 rules across 5 class(es)

  ✓ Saved 100 rules -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Brain-50161\rules\rf

  → SHAP (rule model · rf)

Background dataset has 130 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=130 when initializing the masker.

  SHAP explainer: tree (model=RandomForestClassifier)
  Probe->gene collapse: 936 probes -> 775 genes (16 unmapped)
  Provenance -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Brain-50161\rules\rf\shap\text\probe_to_gene_metadata.csv
  SHAP plots saved -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Brain-50161\rules\rf\shap\plots
  SHAP matrix -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Brain-50161\rules\rf\shap\text\shap_feature_importance_matrix.csv
  Gene lists -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Brain-50161\rules\rf\shap\text\top_shap_genes_by_class.txt

  ✓ SHAP complete → C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Brain-50161\rules\rf\shap

  → Rule extraction (decisiontree)

  ✓ Extracted 7 raw rules from 1 tree(s)

  ✓ Simplified -> 5 rules across 5 class(es)

  ✓ Saved 5 rules -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Brain-50161\rules\dt

  → SHAP (rule model · decisiontree)

Background dataset has 130 samples but max_samples=100. Subsampling to 100 samples for SHAP value computation. To use all samples, set max_samples=130 when initializing the masker.

  SHAP explainer: tree (model=DecisionTreeClassifier)
  Probe->gene collapse: 936 probes -> 775 genes (16 unmapped)
  Provenance -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Brain-50161\rules\dt\shap\text\probe_to_gene_metadata.csv
  SHAP plots saved -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Brain-50161\rules\dt\shap\plots
  SHAP matrix -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Brain-50161\rules\dt\shap\text\shap_feature_importance_matrix.csv
  Gene lists -> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Brain-50161\rules\dt\shap\text\top_shap_genes_by_class.txt

  ✓ SHAP complete → C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Brain-50161\rules\dt\shap

  ✓ Cross-check rf vs decisiontree: 1 identical rule(s), 12 shared gene-direction literal(s) (literal Jaccard=0.04)
-> C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\CuMiDa-Brain-50161\rules\compare

        CuMiDa-Brain-50161 — extracted rules (FS: boruta)
┏━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃        model ┃ n_rules ┃ cls:0 ┃ cls:1 ┃ cls:2 ┃ cls:3 ┃ cls:4 ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━┩
│           rf │     100 │    20 │    20 │    20 │    20 │    20 │
│ decisiontree │       5 │     1 │     1 │     1 │     1 │     1 │
└──────────────┴─────────┴───────┴───────┴───────┴───────┴───────┘

    Cross-check: 1 identical rule(s), 12 shared gene-direction literal(s) (literal Jaccard=0.04)

{'GEO-Breast-20711': {'fs_method': 'mrmr_miq',
  'models': {'rf': {'n_rules': 80,
    'per_class': {'Basal': 20, 'HER2': 20, 'LumA': 20, 'LumB': 20}},
   'decisiontree': {'n_rules': 4,
    'per_class': {'Basal': 1, 'HER2': 1, 'LumA': 1, 'LumB': 1}}},
  'compare': {'n_a': 80,
   'n_b': 4,
   'n_overlap': 1,
   'jaccard': 0.0128,
   'overlap': [{'literals': ['ERBB2=High', 'MMRN1=Low'],
     'consequent': 'Class=HER2',
     'rf_confidence': 1.0,
     'decisiontree_confidence': 1.0}],
   'literal_overlap': 13,
   'literal_jaccard': 0.1066,
   'shared_literals': [{'gene': 'ERBB2',
     'direction': 'High',
     'consequent': 'Class=HER2'},
    {'gene': 'ERBB2', 'direction': 'Low', 'consequent': 'Class=Basal'},
    {'gene': 'ERBB2', 'direction': 'Low', 'consequent': 'Class=LumA'},
    {'gene': 'ERBB2', 'direction': 'Low', 'consequent': 'Class=LumB'},
    {'gene': 'KCNK15', 'direction': 'High', 'consequent': 'Class=LumB'},
    {'gene': 'KCNK15', 'direction': 'Low', 'consequent': 'Class=Basal'},
    {'gene': 'KNL1', 'direction': 'High', 'consequent': 'Class=Basal'},
    {'gene': 'KNL1', 'direction': 'High', 'consequent': 'Class=LumB'},
    {'gene': 'KNL1', 'direction': 'Low', 'consequent': 'Class=LumA'},
    {'gene': 'MMRN1', 'direction': 'Low', 'consequent': 'Class=HER2'},
    {'gene': 'MMRN1', 'direction': 'Low', 'consequent': 'Class=LumB'},
    {'gene': 'TTC30B', 'direction': 'Low', 'consequent': 'Class=Basal'},
    {'gene': 'USP43', 'direction': 'High', 'consequent': 'Class=LumA'}]}},
 'GEO-Mesothelioma-29354': {'fs_method': 'boruta',
  'models': {'rf': {'n_rules': 60, 'per_class': {'0': 20, '1': 20, '2': 20}},
   'decisiontree': {'n_rules': 4, 'per_class': {'0': 1, '1': 2, '2': 1}}},
  'compare': {'n_a': 60,
   'n_b': 4,
   'n_overlap': 3,
   'jaccard': 0.0789,
   'overlap': [{'literals': ['C7orf55-LUC7L2=Low',
      'FADS3=Low',
      'LOC102725263=High',
      'MIR943=High'],
     'consequent': 'Class=0',
     'rf_confidence': 1.0,
     'decisiontree_confidence': 1.0},
    {'literals': ['C7orf55-LUC7L2=High', 'FADS3=Low'],
     'consequent': 'Class=1',
     'rf_confidence': 1.0,
     'decisiontree_confidence': 1.0},
    {'literals': ['FADS3=High'],
     'consequent': 'Class=2',
     'rf_confidence': 0.8333,
     'decisiontree_confidence': 1.0}],
   'literal_overlap': 8,
   'literal_jaccard': 0.3077,
   'shared_literals': [{'gene': 'C7orf55-LUC7L2',
     'direction': 'High',
     'consequent': 'Class=1'},
    {'gene': 'C7orf55-LUC7L2', 'direction': 'Low', 'consequent': 'Class=0'},
    {'gene': 'FADS3', 'direction': 'High', 'consequent': 'Class=2'},
    {'gene': 'FADS3', 'direction': 'Low', 'consequent': 'Class=0'},
    {'gene': 'FADS3', 'direction': 'Low', 'consequent': 'Class=1'},
    {'gene': 'LOC102725263', 'direction': 'High', 'consequent': 'Class=0'},
    {'gene': 'LOC102725263', 'direction': 'Low', 'consequent': 'Class=1'},
    {'gene': 'MIR943', 'direction': 'High', 'consequent': 'Class=0'}]}},
 'GEO-Kidney-36895': {'fs_method': 'boruta',
  'models': {'rf': {'n_rules': 100,
    'per_class': {'0': 10, '1': 20, '2': 20, '3': 20, '4': 20, '6': 10}},
   'decisiontree': {'n_rules': 6,
    'per_class': {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1, '6': 1}}},
  'compare': {'n_a': 100,
   'n_b': 6,
   'n_overlap': 1,
   'jaccard': 0.0118,
   'overlap': [{'literals': ['FYB=Low'],
     'consequent': 'Class=3',
     'rf_confidence': 1.0,
     'decisiontree_confidence': 1.0}],
   'literal_overlap': 17,
   'literal_jaccard': 0.2787,
   'shared_literals': [{'gene': '235894_at',
     'direction': 'High',
     'consequent': 'Class=2'},
    {'gene': '235894_at', 'direction': 'Range', 'consequent': 'Class=1'},
    {'gene': 'CNTROB', 'direction': 'Low', 'consequent': 'Class=6'},
    {'gene': 'FYB', 'direction': 'High', 'consequent': 'Class=0'},
    {'gene': 'FYB', 'direction': 'High', 'consequent': 'Class=1'},
    {'gene': 'FYB', 'direction': 'High', 'consequent': 'Class=2'},
    {'gene': 'FYB', 'direction': 'High', 'consequent': 'Class=4'},
    {'gene': 'FYB', 'direction': 'High', 'consequent': 'Class=6'},
    {'gene': 'FYB', 'direction': 'Low', 'consequent': 'Class=3'},
    {'gene': 'NEK11', 'direction': 'High', 'consequent': 'Class=4'},
    {'gene': 'NEK11', 'direction': 'Low', 'consequent': 'Class=1'},
    {'gene': 'NEK11', 'direction': 'Low', 'consequent': 'Class=2'},
    {'gene': 'NEK11', 'direction': 'Low', 'consequent': 'Class=6'},
    {'gene': 'PECAM1', 'direction': 'High', 'consequent': 'Class=0'},
    {'gene': 'PECAM1', 'direction': 'Low', 'consequent': 'Class=1'},
    {'gene': 'PECAM1', 'direction': 'Low', 'consequent': 'Class=2'},
    {'gene': 'PECAM1', 'direction': 'Range', 'consequent': 'Class=6'}]}},
 'GEO-Colon-68468': {'fs_method': 'mrmr_miq',
  'models': {'rf': {'n_rules': 80,
    'per_class': {'0': 20, '1': 20, '2': 20, '3': 20}},
   'decisiontree': {'n_rules': 7,
    'per_class': {'0': 4, '1': 1, '2': 1, '3': 1}}},
  'compare': {'n_a': 80,
   'n_b': 7,
   'n_overlap': 1,
   'jaccard': 0.0132,
   'overlap': [{'literals': ['SFTPA2=High', 'SFTPB=High'],
     'consequent': 'Class=2',
     'rf_confidence': 1.0,
     'decisiontree_confidence': 1.0}],
   'literal_overlap': 18,
   'literal_jaccard': 0.2195,
   'shared_literals': [{'gene': 'AGMAT',
     'direction': 'High',
     'consequent': 'Class=1'},
    {'gene': 'CA2', 'direction': 'High', 'consequent': 'Class=0'},
    {'gene': 'COLEC11', 'direction': 'High', 'consequent': 'Class=1'},
    {'gene': 'COLEC11', 'direction': 'Low', 'consequent': 'Class=0'},
    {'gene': 'GUCA2A', 'direction': 'High', 'consequent': 'Class=3'},
    {'gene': 'GUCA2A', 'direction': 'Low', 'consequent': 'Class=0'},
    {'gene': 'GUCA2A', 'direction': 'Low', 'consequent': 'Class=1'},
    {'gene': 'MYOT', 'direction': 'High', 'consequent': 'Class=3'},
    {'gene': 'P2RY14', 'direction': 'Low', 'consequent': 'Class=1'},
    {'gene': 'SFTPA2', 'direction': 'High', 'consequent': 'Class=2'},
    {'gene': 'SFTPA2', 'direction': 'Low', 'consequent': 'Class=0'},
    {'gene': 'SFTPA2', 'direction': 'Low', 'consequent': 'Class=1'},
    {'gene': 'SFTPA2', 'direction': 'Low', 'consequent': 'Class=3'},
    {'gene': 'SFTPB', 'direction': 'High', 'consequent': 'Class=0'},
    {'gene': 'SFTPB', 'direction': 'High', 'consequent': 'Class=2'},
    {'gene': 'SFTPB', 'direction': 'Low', 'consequent': 'Class=0'},
    {'gene': 'SOX10', 'direction': 'High', 'consequent': 'Class=3'},
    {'gene': 'SOX10', 'direction': 'Low', 'consequent': 'Class=0'}]}},
 'GEO-MultiCancer-68606': {'fs_method': 'boruta',
  'models': {'rf': {'n_rules': 100,
    'per_class': {'0': 16,
     '10': 6,
     '11': 20,
     '12': 2,
     '13': 20,
     '2': 10,
     '3': 4,
     '5': 6,
     '8': 8,
     '9': 8}},
   'decisiontree': {'n_rules': 3, 'per_class': {'0': 1, '13': 1, '9': 1}}},
  'compare': {'n_a': 100,
   'n_b': 3,
   'n_overlap': 0,
   'jaccard': 0.0,
   'overlap': [],
   'literal_overlap': 6,
   'literal_jaccard': 0.0262,
   'shared_literals': [{'gene': 'ALDH3A2',
     'direction': 'High',
     'consequent': 'Class=0'},
    {'gene': 'ALDH3A2', 'direction': 'Low', 'consequent': 'Class=13'},
    {'gene': 'CALML4', 'direction': 'High', 'consequent': 'Class=13'},
    {'gene': 'LOXL1', 'direction': 'Low', 'consequent': 'Class=0'},
    {'gene': 'LOXL1', 'direction': 'Low', 'consequent': 'Class=13'},
    {'gene': 'ZFAND5', 'direction': 'High', 'consequent': 'Class=9'}]}},
 'CuMiDa-Ovary-6008': {'fs_method': 'boruta',
  'models': {'rf': {'n_rules': 80,
    'per_class': {'0': 20, '1': 20, '2': 20, '3': 20}},
   'decisiontree': {'n_rules': 7,
    'per_class': {'0': 1, '1': 3, '2': 1, '3': 2}}},
  'compare': {'n_a': 80,
   'n_b': 7,
   'n_overlap': 1,
   'jaccard': 0.0135,
   'overlap': [{'literals': ['AP2A2=High'],
     'consequent': 'Class=0',
     'rf_confidence': 1.0,
     'decisiontree_confidence': 1.0}],
   'literal_overlap': 13,
   'literal_jaccard': 0.071,
   'shared_literals': [{'gene': 'ADH1C',
     'direction': 'High',
     'consequent': 'Class=3'},
    {'gene': 'AGR2', 'direction': 'High', 'consequent': 'Class=2'},
    {'gene': 'AGR2', 'direction': 'Low', 'consequent': 'Class=3'},
    {'gene': 'AP2A2', 'direction': 'High', 'consequent': 'Class=0'},
    {'gene': 'AP2A2', 'direction': 'Low', 'consequent': 'Class=1'},
    {'gene': 'AP2A2', 'direction': 'Low', 'consequent': 'Class=2'},
    {'gene': 'FUT6', 'direction': 'High', 'consequent': 'Class=1'},
    {'gene': 'FUT6', 'direction': 'Low', 'consequent': 'Class=3'},
    {'gene': 'MYL9', 'direction': 'High', 'consequent': 'Class=3'},
    {'gene': 'MYL9', 'direction': 'Low', 'consequent': 'Class=1'},
    {'gene': 'PTPRR', 'direction': 'High', 'consequent': 'Class=2'},
    {'gene': 'VLDLR', 'direction': 'High', 'consequent': 'Class=1'},
    {'gene': 'VLDLR', 'direction': 'Low', 'consequent': 'Class=3'}]}},
 'CuMiDa-Brain-15824': {'fs_method': 'boruta',
  'models': {'rf': {'n_rules': 80,
    'per_class': {'0': 20, '1': 20, '2': 20, '3': 20}},
   'decisiontree': {'n_rules': 5,
    'per_class': {'0': 1, '1': 2, '2': 1, '3': 1}}},
  'compare': {'n_a': 80,
   'n_b': 5,
   'n_overlap': 1,
   'jaccard': 0.0123,
   'overlap': [{'literals': ['STK11=High'],
     'consequent': 'Class=3',
     'rf_confidence': 1.0,
     'decisiontree_confidence': 1.0}],
   'literal_overlap': 9,
   'literal_jaccard': 0.0667,
   'shared_literals': [{'gene': 'MFAP5',
     'direction': 'High',
     'consequent': 'Class=0'},
    {'gene': 'MFAP5', 'direction': 'High', 'consequent': 'Class=1'},
    {'gene': 'MFAP5', 'direction': 'Low', 'consequent': 'Class=2'},
    {'gene': 'RP3-486D24.1', 'direction': 'Low', 'consequent': 'Class=1'},
    {'gene': 'STK11', 'direction': 'High', 'consequent': 'Class=3'},
    {'gene': 'STK11', 'direction': 'Low', 'consequent': 'Class=1'},
    {'gene': 'STK11', 'direction': 'Low', 'consequent': 'Class=2'},
    {'gene': 'ZXDA', 'direction': 'High', 'consequent': 'Class=0'},
    {'gene': 'ZXDA', 'direction': 'Low', 'consequent': 'Class=1'}]}},
 'CuMiDa-Breast-26304': {'fs_method': 'mrmr_miq',
  'models': {'rf': {'n_rules': 80,
    'per_class': {'0': 20, '1': 20, '2': 20, '3': 20}},
   'decisiontree': {'n_rules': 9,
    'per_class': {'0': 3, '1': 3, '2': 2, '3': 1}}},
  'compare': {'n_a': 80,
   'n_b': 9,
   'n_overlap': 0,
   'jaccard': 0.0,
   'overlap': [],
   'literal_overlap': 23,
   'literal_jaccard': 0.1456,
   'shared_literals': [{'gene': 'ACTG2',
     'direction': 'High',
     'consequent': 'Class=0'},
    {'gene': 'A_24_P934497', 'direction': 'High', 'consequent': 'Class=1'},
    {'gene': 'A_24_P934497', 'direction': 'Low', 'consequent': 'Class=0'},
    {'gene': 'A_24_P934497', 'direction': 'Low', 'consequent': 'Class=2'},
    {'gene': 'BC040195', 'direction': 'High', 'consequent': 'Class=0'},
    {'gene': 'COMP', 'direction': 'High', 'consequent': 'Class=2'},
    {'gene': 'HTRA3', 'direction': 'High', 'consequent': 'Class=2'},
    {'gene': 'HTRA3', 'direction': 'Low', 'consequent': 'Class=0'},
    {'gene': 'MUCL1', 'direction': 'Low', 'consequent': 'Class=1'},
    {'gene': 'NM_000088', 'direction': 'High', 'consequent': 'Class=1'},
    {'gene': 'NM_000088', 'direction': 'Low', 'consequent': 'Class=0'},
    {'gene': 'NM_000088', 'direction': 'Range', 'consequent': 'Class=2'},
    {'gene': 'PTN', 'direction': 'High', 'consequent': 'Class=3'},
    {'gene': 'PTN', 'direction': 'Low', 'consequent': 'Class=0'},
    {'gene': 'PTN', 'direction': 'Low', 'consequent': 'Class=1'},
    {'gene': 'PTN', 'direction': 'Low', 'consequent': 'Class=2'},
    {'gene': 'REXO2', 'direction': 'High', 'consequent': 'Class=1'},
    {'gene': 'REXO2', 'direction': 'Low', 'consequent': 'Class=0'},
    {'gene': 'REXO2', 'direction': 'Low', 'consequent': 'Class=1'},
    {'gene': 'RND3', 'direction': 'Low', 'consequent': 'Class=1'},
    {'gene': 'SIX1', 'direction': 'High', 'consequent': 'Class=0'},
    {'gene': 'SIX1', 'direction': 'Low', 'consequent': 'Class=1'},
    {'gene': 'THC2271659', 'direction': 'Low', 'consequent': 'Class=3'}]}},
 'CuMiDa-Leukemia-28497': {'fs_method': 'boruta',
  'models': {'rf': {'n_rules': 100,
    'per_class': {'1': 20, '2': 20, '4': 20, '5': 20, '6': 20}},
   'decisiontree': {'n_rules': 5,
    'per_class': {'1': 1, '2': 1, '4': 1, '5': 1, '6': 1}}},
  'compare': {'n_a': 100,
   'n_b': 5,
   'n_overlap': 1,
   'jaccard': 0.0108,
   'overlap': [{'literals': ['PBX1=High'],
     'consequent': 'Class=6',
     'rf_confidence': 1.0,
     'decisiontree_confidence': 1.0}],
   'literal_overlap': 17,
   'literal_jaccard': 0.0769,
   'shared_literals': [{'gene': 'ARHGEF12',
     'direction': 'High',
     'consequent': 'Class=1'},
    {'gene': 'BCL11B', 'direction': 'High', 'consequent': 'Class=5'},
    {'gene': 'DSC3', 'direction': 'High', 'consequent': 'Class=1'},
    {'gene': 'DSC3', 'direction': 'Low', 'consequent': 'Class=2'},
    {'gene': 'LAMP5', 'direction': 'High', 'consequent': 'Class=4'},
    {'gene': 'LAMP5', 'direction': 'Low', 'consequent': 'Class=1'},
    {'gene': 'LAMP5', 'direction': 'Low', 'consequent': 'Class=2'},
    {'gene': 'PAX5', 'direction': 'High', 'consequent': 'Class=1'},
    {'gene': 'PAX5', 'direction': 'High', 'consequent': 'Class=2'},
    {'gene': 'PAX5', 'direction': 'High', 'consequent': 'Class=4'},
    {'gene': 'PAX5', 'direction': 'Low', 'consequent': 'Class=5'},
    {'gene': 'PBX1', 'direction': 'High', 'consequent': 'Class=6'},
    {'gene': 'PBX1', 'direction': 'Low', 'consequent': 'Class=1'},
    {'gene': 'PBX1', 'direction': 'Low', 'consequent': 'Class=2'},
    {'gene': 'PBX1', 'direction': 'Low', 'consequent': 'Class=4'},
    {'gene': 'PBX1', 'direction': 'Low', 'consequent': 'Class=5'},
    {'gene': 'ZCCHC24', 'direction': 'High', 'consequent': 'Class=2'}]}},
 'CuMiDa-Colorectal-41657': {'fs_method': 'boruta',
  'models': {'rf': {'n_rules': 80,
    'per_class': {'0': 20, '1': 20, '2': 20, '3': 20}},
   'decisiontree': {'n_rules': 5,
    'per_class': {'0': 1, '1': 2, '2': 1, '3': 1}}},
  'compare': {'n_a': 80,
   'n_b': 5,
   'n_overlap': 0,
   'jaccard': 0.0,
   'overlap': [],
   'literal_overlap': 9,
   'literal_jaccard': 0.0443,
   'shared_literals': [{'gene': 'ANKAR',
     'direction': 'Low',
     'consequent': 'Class=0'},
    {'gene': 'A_24_P76288', 'direction': 'High', 'consequent': 'Class=2'},
    {'gene': 'EFS', 'direction': 'High', 'consequent': 'Class=0'},
    {'gene': 'EFS', 'direction': 'Low', 'consequent': 'Class=1'},
    {'gene': 'MET', 'direction': 'High', 'consequent': 'Class=1'},
    {'gene': 'PSMA7', 'direction': 'Low', 'consequent': 'Class=2'},
    {'gene': 'TMX1', 'direction': 'High', 'consequent': 'Class=2'},
    {'gene': 'TMX1', 'direction': 'Low', 'consequent': 'Class=1'},
    {'gene': 'TSPAN4', 'direction': 'Low', 'consequent': 'Class=1'}]}},
 'CuMiDa-Breast-45827': {'fs_method': 'boruta',
  'models': {'rf': {'n_rules': 100,
    'per_class': {'0': 17, '1': 20, '2': 20, '3': 20, '4': 3, '5': 20}},
   'decisiontree': {'n_rules': 6,
    'per_class': {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1, '5': 1}}},
  'compare': {'n_a': 100,
   'n_b': 6,
   'n_overlap': 0,
   'jaccard': 0.0,
   'overlap': [],
   'literal_overlap': 6,
   'literal_jaccard': 0.0194,
   'shared_literals': [{'gene': 'ERBB2',
     'direction': 'Low',
     'consequent': 'Class=3'},
    {'gene': 'ESR1', 'direction': 'High', 'consequent': 'Class=3'},
    {'gene': 'ESR1', 'direction': 'Low', 'consequent': 'Class=0'},
    {'gene': 'GRB7', 'direction': 'High', 'consequent': 'Class=0'},
    {'gene': 'GRB7', 'direction': 'Low', 'consequent': 'Class=1'},
    {'gene': 'SPAG5', 'direction': 'Low', 'consequent': 'Class=3'}]}},
 'CuMiDa-Brain-50161': {'fs_method': 'boruta',
  'models': {'rf': {'n_rules': 100,
    'per_class': {'0': 20, '1': 20, '2': 20, '3': 20, '4': 20}},
   'decisiontree': {'n_rules': 5,
    'per_class': {'0': 1, '1': 1, '2': 1, '3': 1, '4': 1}}},
  'compare': {'n_a': 100,
   'n_b': 5,
   'n_overlap': 1,
   'jaccard': 0.0102,
   'overlap': [{'literals': ['TSPAN6=Low'],
     'consequent': 'Class=3',
     'rf_confidence': 0.9286,
     'decisiontree_confidence': 1.0}],
   'literal_overlap': 12,
   'literal_jaccard': 0.0427,
   'shared_literals': [{'gene': 'EFCAB1',
     'direction': 'High',
     'consequent': 'Class=0'},
    {'gene': 'EFCAB1', 'direction': 'Low', 'consequent': 'Class=1'},
    {'gene': 'EFCAB1', 'direction': 'Low', 'consequent': 'Class=4'},
    {'gene': 'MAD2L1', 'direction': 'High', 'consequent': 'Class=1'},
    {'gene': 'MAD2L1', 'direction': 'Low', 'consequent': 'Class=4'},
    {'gene': 'PHF21B', 'direction': 'High', 'consequent': 'Class=2'},
    {'gene': 'PHF21B', 'direction': 'Low', 'consequent': 'Class=1'},
    {'gene': 'PHF21B', 'direction': 'Low', 'consequent': 'Class=4'},
    {'gene': 'TSPAN6', 'direction': 'High', 'consequent': 'Class=0'},
    {'gene': 'TSPAN6', 'direction': 'High', 'consequent': 'Class=1'},
    {'gene': 'TSPAN6', 'direction': 'High', 'consequent': 'Class=2'},
    {'gene': 'TSPAN6', 'direction': 'Low', 'consequent': 'Class=3'}]}}}

## Gene Descriptions — Biological Annotation (separate step)

Enrich the genes appearing in the rules with biological info from each dataset's
platform file (`Platform_Annotations/…`): **Gene title, Entrez ID, GenBank,
chromosome, GO Biological Process / Cellular Component / Molecular Function**.
Writes `gene_description.csv` + `gene_description.md` next to each
`genes_in_rules.csv` under `outputs/{dataset}/rules/{rf,dt}/`.

This is a **separate step**: it reads existing rule outputs (no re-training), so
it can run any time after rule extraction.

In [ ]:
# Separate step — annotate rule genes from the platform files.
gene_desc = pipe.describe_genes_in_rules(dataset_names=None)
gene_desc

## Inspect Outputs

In [3]:
DATASET = 'GEO-Breast-20711'
rules_root = pipe.output_root / DATASET / 'rules'
print('Rules root:', rules_root)
for sub in sorted(p.name for p in rules_root.iterdir() if p.is_dir()):
    print(' ', sub, '→', [f.name for f in sorted((rules_root / sub).iterdir())])

Rules root: C:\Users\Bao Nguyen\LearningWithClaude\LV_code\outputs\GEO-Breast-20711\rules
  compare → ['crosscheck.json']
  dt → ['rules.csv', 'rules.json', 'rules_human.txt', 'rules_summary.json']
  rf → ['rules.csv', 'rules.json', 'rules_human.txt', 'rules_summary.json']

### Random Forest rules (ensemble — many candidate rules)

In [4]:
rf_rules = pd.read_csv(rules_root / 'rf' / 'rules.csv')
rf_summary = json.loads((rules_root / 'rf' / 'rules_summary.json').read_text())
print('RF set-level:', {k: rf_summary[k] for k in ('n_rules', 'coverage', 'mean_fidelity')})
rf_rules.head(10)

RF set-level: {'n_rules': 80, 'coverage': 0.9778, 'mean_fidelity': 0.9567}

,antecedents,consequents,support,confidence,error,lift,class_specificity,fidelity,strength_score,n_conditions
0,"242960_at<=4.079, ERBB2<=11.17, MYB>9.031, KNL...",Class=LumA,0.1333,1.0000,0.0000,6.9231,1.0000,1.0000,0.923077,5
1,"241536_at<=5.086, CDK12<=8.472, KNL1<=5.627, E...",Class=LumA,0.1444,0.9231,0.0769,6.3905,0.8462,1.0000,0.852071,4
2,"233392_at<=3.523, CCNB2<=6.637, SLC40A1>5.814",Class=LumA,0.1444,0.9231,0.0769,6.3905,0.8462,0.9231,0.852071,3
3,"241536_at<=5.086, MYB>9.018, SVEP1>2.637, TPX2...",Class=LumA,0.1444,0.9231,0.0769,6.3905,0.8462,0.9231,0.852071,5
4,"MYH11<=6.028, CCNB2>6.221, ERBB2>5.481",Class=HER2,0.2444,1.0000,0.0000,3.4615,1.0000,1.0000,0.846154,3
5,"SVEP1<=3.288, ERBB2>10.78",Class=HER2,0.2444,1.0000,0.0000,3.4615,1.0000,1.0000,0.846154,2
6,"CDK1>6.359, ERBB2>4.344",Class=HER2,0.2444,1.0000,0.0000,3.4615,1.0000,1.0000,0.846154,2
7,"LOC401433<=3.916, ERBB2>5.573",Class=HER2,0.2444,1.0000,0.0000,3.4615,1.0000,1.0000,0.846154,2
8,"TNFRSF10B<=4.676, CCNB2>6.637, ERBB2>5.552",Class=HER2,0.2444,1.0000,0.0000,3.4615,1.0000,1.0000,0.846154,3
9,"RNF186<=4.339, CCNB2<=6.637, USP43>5.194",Class=LumA,0.1222,1.0000,0.0000,6.9231,1.0000,1.0000,0.846154,3

### Decision Tree rules (single tree — few, exact, easy to read)

In [5]:
dt_rules = pd.read_csv(rules_root / 'dt' / 'rules.csv')
print((rules_root / 'dt' / 'rules_human.txt').read_text())
dt_rules

IF 242904_x_at<=4.787 AND ERBB2<=4.28 AND KNL1<=5.87 AND USP43>5.017 THEN Class=LumA (conf=0.93, support=0.16, lift=6.43, fidelity=1.00)
IF 242904_x_at<=4.787 AND ERBB2>4.28 AND KCNK15>2.387 THEN Class=HER2 (conf=1.00, support=0.21, lift=3.46, fidelity=1.00)
IF 242904_x_at<=4.787 AND ERBB2<=4.28 AND KNL1>5.87 AND KCNK15>4.021 THEN Class=LumB (conf=1.00, support=0.17, lift=4.09, fidelity=1.00)
IF 242904_x_at<=4.787 AND ERBB2>4.28 AND KCNK15<=2.387 THEN Class=HER2 (conf=1.00, support=0.03, lift=3.46, fidelity=1.00)

,antecedents,consequents,support,confidence,error,lift,class_specificity,fidelity,strength_score,n_conditions
0,"242904_x_at<=4.787, ERBB2<=4.28, KNL1<=5.87, U...",Class=LumA,0.1556,0.9286,0.0714,6.4286,0.8571,1.0,0.928571,4
1,"242904_x_at<=4.787, ERBB2>4.28, KCNK15>2.387",Class=HER2,0.2111,1.0000,0.0000,3.4615,1.0000,1.0,0.730769,3
2,"242904_x_at<=4.787, ERBB2<=4.28, KNL1>5.87, KC...",Class=LumB,0.1667,1.0000,0.0000,4.0909,1.0000,1.0,0.681818,4
3,"242904_x_at<=4.787, ERBB2>4.28, KCNK15<=2.387",Class=HER2,0.0333,1.0000,0.0000,3.4615,1.0000,1.0,0.115385,3

### Rule count per class (RF)

In [6]:
rf_rules.groupby('consequents').agg(
    n_rules=('consequents', 'count'),
    mean_confidence=('confidence', 'mean'),
    mean_fidelity=('fidelity', 'mean'),
    mean_support=('support', 'mean'),
    mean_lift=('lift', 'mean'),
).round(4)

             n_rules  mean_confidence  mean_fidelity  mean_support  mean_lift
consequents
Class=Basal       20           0.8868         0.9472        0.2706     2.9560
Class=HER2        20           1.0000         1.0000        0.2444     3.4615
Class=LumA        20           0.9367         0.9608        0.1344     6.4847
Class=LumB        20           0.9205         0.9259        0.1972     3.7655

## Cross-Check: RF vs Decision Tree

Rules confirmed by **both** a single tree and the ensemble are the
highest-trust set. Two levels are reported:
- **identical rules** — same (gene, direction) literal set + class (strict)
- **shared literals** — single `GENE=High/Low → Class` facts both models agree on
  (lenient; informative even when full antecedents differ).

In [7]:
cc = json.loads((rules_root / 'compare' / 'crosscheck.json').read_text())
print(f"{cc['model_a']} ({cc['n_a']} rules) vs {cc['model_b']} ({cc['n_b']} rules)")
print(f"Identical rules : {cc['n_overlap']} (Jaccard={cc['jaccard']})")
print(f"Shared literals : {cc['literal_overlap']} (Jaccard={cc['literal_jaccard']})")
print()
pd.DataFrame(cc['shared_literals'])

rf (80 rules) vs decisiontree (4 rules)
Identical rules : 0 (Jaccard=0.0)
Shared literals : 8 (Jaccard=0.0645)

          gene direction  consequent
0  242904_x_at       Low  Class=LumA
1        ERBB2      High  Class=HER2
2        ERBB2       Low  Class=LumA
3        ERBB2       Low  Class=LumB
4       KCNK15      High  Class=LumB
5         KNL1      High  Class=LumB
6         KNL1       Low  Class=LumA
7        USP43      High  Class=LumA

## Faithfulness Check

Verify a rule's confidence against the raw data using the exact per-probe
conditions stored in `antecedent_raw`. Expected: recomputed ≈ reported.

In [ ]:
from src.helper import load_dataset, load_fs_reduced_matrix

ds_cfg = pipe.config_loader.get_dataset_config(DATASET)
fs_method = results[DATASET]['fs_method']
data = load_dataset(dataset_path=Path(ds_cfg['path']), dataset_type=ds_cfg.get('type', 'auto'))
y = data['y']

# Load the FS feature matrix the rule models were trained on.
if fs_method == 'raw':
    X_sel, feat = data['X'], list(data['feature_names'])
else:
    csv_dir = pipe.output_root / 'feature_selection' / DATASET / fs_method / 'processed_datasets'
    X_sel, feat = load_fs_reduced_matrix(csv_dir)

cards = json.loads((rules_root / 'rf' / 'rules.json').read_text())
r = cards['rules'][0]
print('Rule:', r['text'])
print('Reported:', r['metrics'])

mask = np.ones(len(y), dtype=bool)
for cond in r['antecedent_raw']:
    idx = feat.index(cond['probe'])
    mask &= (X_sel[:, idx] <= cond['threshold']) if cond['op'] == '<=' else (X_sel[:, idx] > cond['threshold'])

cls = r['consequent']['class_idx']
n_ant = int(mask.sum())
emp_conf = (y[mask] == cls).mean() if n_ant else 0
print(f"\nAntecedent fires on {n_ant} samples; empirical confidence = {emp_conf:.4f}")
print(f"Match reported confidence: {abs(emp_conf - r['metrics']['confidence']) < 1e-3}")

## Export Summary

In [9]:
rows = []
for ds_name, info in results.items():
    for model_name, summ in info.get('models', {}).items():
        rows.append({
            'dataset': ds_name,
            'fs_method': info['fs_method'],
            'model': model_name,
            'n_rules': summ['n_rules'],
            'identical_overlap': (info.get('compare') or {}).get('n_overlap'),
            'literal_overlap': (info.get('compare') or {}).get('literal_overlap'),
        })
pd.DataFrame(rows)

,dataset,fs_method,model,n_rules,identical_overlap,literal_overlap
0,GEO-Breast-20711,mrmr_miq,rf,80,0,8
1,GEO-Breast-20711,mrmr_miq,decisiontree,4,0,8